sudo: required
matrix:
  fast_finish: true
  include:
    - python: "3.5.3"
      env: TOXENV=lint
    - python: "3.5.3"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=build
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
    - python: "3.8-dev"
      env: TOXENV=py38
      dist: xenial

install: pip install -U tox coveralls
language: python
script: tox
after_success: coveralls
